### ISSUE TITLE
Request the Landmark-clean dataset

### ISSUE THREAD

**Issue by willard-yuan** [fongyk/graph-attention#1]
@fongyk I'm sorry to disturb you. I find you have Landmark-clean dataset, and I have found it about two years. Would you mind to share the Landmark-clean dataset to me?

Thanks a lot.

**Comment by fongyk** [comment]
We downloaded the landmark-clean dataset from [http://download.europe.naverlabs.com/Computer-Vision-CodeandModels/](url) provided by [https://europe.naverlabs.com/Research/Computer-Vision/Learning-Visual-Representations/Deep-Image-Retrieval/](url). Maybe that's what you need.

**Comment by willard-yuan** [comment]
@fongyk Thank you for sharing the URLs. I have tried these before. But Some of the URLs are broken. The Landmark-clean dataset I obtained it's not complete. Do you have any method to obtain the complete Landmark-clean dataset?

**Comment by fongyk** [comment]
I'm sorry that we are also using the incomplete version of the dataset.  Maybe some urls have already been dead, and I can do nothing with it.

**Comment by willard-yuan** [comment]
Using the incomplete version of the dataset, I just get 0.7-0.8 MAP on Oxford Building dataset as best as I can.  It's very disappointed  that they don't share the images.

**Comment by fongyk** [comment]
Actually, I didn't re-implement that Deep Retrieval model, so I don't know what the mAP can be on Oxford based on the current training data. Perhaps some training tricks can be explored.

**Comment by willard-yuan** [comment]
Thank you for you fast reply. Thanks a lot.
